/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginproyecto;


import Panel.CorteCaja;
import Panel.Inventario;
import Panel.Notificaciones;
import Panel.Transacciones;
import Panel.Ventas;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;
import paneles.CambiaPanel;

/**
 *
 * @author herre
 */
public class FrmVentas extends javax.swing.JFrame {
    private boolean menuAbierto = true;
    private final int ANCHO_MENU = 190;
    private final int ANCHO_MINIMO = 60;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmVentas.class.getName());

   
    public FrmVentas() {
        initComponents();
        
        
        this.setLocationRelativeTo(null);
        this.btnventas.setSelected(true);
        JPanel Ventas;
        
        
        
        new CambiaPanel(panelPrincipal, new Ventas());
        
    }
    
    public void MostrarFecha(){
        Date d = new Date ();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/YYYY");
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        panelArriba = new javax.swing.JPanel();
        btnmenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        btnventas = new javax.swing.JButton();
        btncaja = new javax.swing.JButton();
        btninventario = new javax.swing.JButton();
        btnnoti = new javax.swing.JButton();
        btnTrans = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        panelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelArriba.setBackground(new java.awt.Color(0, 0, 0));
        panelArriba.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnmenu.setBackground(new java.awt.Color(0, 0, 0));
        btnmenu.setForeground(new java.awt.Color(255, 255, 255));
        btnmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu.png"))); // NOI18N
        btnmenu.setToolTipText("");
        btnmenu.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmenu.addActionListener(this::btnmenuActionPerformed);
        panelArriba.add(btnmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 47, 38));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo_Horizontal.png"))); // NOI18N
        panelArriba.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 50));

        panel.add(panelArriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 60));

        panelMenu.setBackground(new java.awt.Color(0, 0, 0));

        btnventas.setBackground(new java.awt.Color(102, 102, 102));
        btnventas.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btnventas.setForeground(new java.awt.Color(255, 255, 255));
        btnventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/etiqueta-de-venta.png"))); // NOI18N
        btnventas.setText("Ventas");
        btnventas.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnventas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnventasMouseClicked(evt);
            }
        });
        btnventas.addActionListener(this::btnventasActionPerformed);

        btncaja.setBackground(new java.awt.Color(102, 102, 102));
        btncaja.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btncaja.setForeground(new java.awt.Color(255, 255, 255));
        btncaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lista-de-verificacion.png"))); // NOI18N
        btncaja.setText("Corte de caja");
        btncaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncajaMouseClicked(evt);
            }
        });
        btncaja.addActionListener(this::btncajaActionPerformed);

        btninventario.setBackground(new java.awt.Color(102, 102, 102));
        btninventario.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btninventario.setForeground(new java.awt.Color(255, 255, 255));
        btninventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inventario-disponible.png"))); // NOI18N
        btninventario.setText("Inventario");
        btninventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btninventario.addActionListener(this::btninventarioActionPerformed);

        btnnoti.setBackground(new java.awt.Color(102, 102, 102));
        btnnoti.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btnnoti.setForeground(new java.awt.Color(255, 255, 255));
        btnnoti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/activo.png"))); // NOI18N
        btnnoti.setText("Notificaciones");
        btnnoti.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnnoti.addActionListener(this::btnnotiActionPerformed);

        btnTrans.setBackground(new java.awt.Color(102, 102, 102));
        btnTrans.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btnTrans.setForeground(new java.awt.Color(255, 255, 255));
        btnTrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/transaccion.png"))); // NOI18N
        btnTrans.setText("Transacciones");
        btnTrans.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTrans.addActionListener(this::btnTransActionPerformed);

        jButton7.setBackground(new java.awt.Color(102, 102, 102));
        jButton7.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 204, 0));
        jButton7.setText("Cerrar Sesión");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(this::jButton7ActionPerformed);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 153, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("OPCIONES");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 36, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btnventas, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btncaja, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btninventario, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btnnoti))
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btnTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnventas, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btncaja, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btninventario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnnoti, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        panel.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, 570));

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setLayout(new javax.swing.BoxLayout(panelPrincipal, javax.swing.BoxLayout.LINE_AXIS));
        panel.add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 810, 550));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnventasActionPerformed
        new CambiaPanel(panelPrincipal, new Ventas());
    }//GEN-LAST:event_btnventasActionPerformed

    private void btninventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninventarioActionPerformed
        new CambiaPanel(panelPrincipal, new Inventario());
    }//GEN-LAST:event_btninventarioActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
     int posicion = this.panelMenu.getX();
        if (posicion > -1) {
            Animacion.Animacion.mover_izquierda(0, -190, 2, 2, panelMenu);
            
        }else{
            Animacion.Animacion.mover_derecha(-190, 0, 2, 2, panelMenu);
            
            
            
        }
    }//GEN-LAST:event_btnmenuActionPerformed

    private void btncajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncajaActionPerformed
        new CambiaPanel(panelPrincipal, new CorteCaja());
    }//GEN-LAST:event_btncajaActionPerformed

    private void btncajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncajaMouseClicked
       
    }//GEN-LAST:event_btncajaMouseClicked

    private void btnventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnventasMouseClicked
        
    }//GEN-LAST:event_btnventasMouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        this.dispose();
        LoginPrincipal_1 Lp= new LoginPrincipal_1();
        Lp.setVisible(true);
    }//GEN-LAST:event_jButton7MouseClicked

    private void btnnotiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnotiActionPerformed
        new CambiaPanel(panelPrincipal, new Notificaciones());
    }//GEN-LAST:event_btnnotiActionPerformed

    private void btnTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransActionPerformed
        new CambiaPanel(panelPrincipal, new Transacciones());
    }//GEN-LAST:event_btnTransActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmVentas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTrans;
    private javax.swing.JButton btncaja;
    private javax.swing.JButton btninventario;
    private javax.swing.JButton btnmenu;
    private javax.swing.JButton btnnoti;
    private javax.swing.JButton btnventas;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelArriba;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables

}